<?php
/**
 * @author      Oleh Kravets <oleh@openstream.ch>
 * @copyright   Copyright (c) 2020 Openstream Internet Solutions  (https://www.openstream.ch)
 * @license     MIT License
 */
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<div class="admin__field admin__field-option field-email">
    <input id="send_email_copy_only" name="invoice[send_email_copy_only]" value="1" type="checkbox"
           class="admin__control-checkbox" />
    <label class="admin__field-label" for="send_email_copy_only">
        <?= $block->escapeHtml(__('Email Copy Only (Do not sent to customer)')) ?>
    </label>
</div>
<script type="text/javascript">
    
</script>